### ISSUE TITLE
HomeKit just shows blank screen

### ISSUE THREAD

**Issue by thieren** [koryhutchison/homebridge-opensprinkler-api#13]
**Describe The Bug:**
After setting the plugin up and adding the accessory to HomeKit it shows the appropriate irrigation service tile. But most of the time when I tap on it it just shows a blank screen. I can scroll down (approximately 2 screen lengths) to get to the settings. But nothing interesting there.
It worked exactly one time and I could start two zones. After closing and reopening the tile the blank screen reappeared.

**Expected behavior:**
Finding the valves/zones there to turn on/off.

**Logs:**

There was no error in the logs:
```
[19.7.2022, 08:29:32] Registering platform 'homebridge-opensprinkler-api.HomebridgeOpenSprinklerApi'
[19.7.2022, 08:29:32] [homebridge-opensprinkler-api] Loaded homebridge-opensprinkler-api v2.0.0 child bridge successfully
[19.7.2022, 08:29:32] Loaded 1 cached accessories from cachedAccessories.0EB8293EC388.
[19.7.2022, 08:29:32] [homebridge-opensprinkler-api] Loading accessory from cache: OpenSprinkler
[19.7.2022, 08:29:32] Homebridge v1.5.0 (HAP v0.10.2) (homebridge-opensprinkler-api) is running on port 36505.
[19.7.2022, 08:29:32] [homebridge-opensprinkler-api] Restoring existing accessory from cache: OpenSprinkler
```

**Plugin Config:**

```json
{
            "password": {
                "plain": "****"
            },
            "valves": [
                {
                    "name": "Rasen Mitte",
                    "defaultDuration": 1200
                },
                {
                    "name": "Rasen Rand",
                    "defaultDuration": 1200
                },
                {
                    "name": "Koniferen",
                    "defaultDuration": 1800
                },
                {
                    "name": "Spielhaus",
                    "defaultDuration": 600
                },
                {
                    "name": "Rasen Seite",
                    "defaultDuration": 1500
                },
                {
                    "name": "Beet vorn",
                    "defaultDuration": 1800
                },
                {
                    "name": "Rasen vorn",
                    "defaultDuration": 600
                }
            ],
            "host": "10.2.2.21",
            "pollInterval": 15,
            "rainDelay": 12,
            "platform": "HomebridgeOpenSprinklerApi",
            "_bridge": {
                "username": "0E:B8:29:3E:C3:88",
                "port": 36505
            }
        }
```

**Screenshots:**
![IMG_3423](https://user-images.githubusercontent.com/22128659/179706834-03be7a27-6adc-407e-a057-9a73f705207d.PNG)

**Environment:**

* **Plugin Version**: 2.0.0
* **Homebridge Version**: 1.5.0
* **Node.js Version**: 16.16.0
* **NPM Version**: 8.11.0
* **Operating System**: Ubuntu

**Comment by thieren** [comment]
Have tested a little more: if I continuously tap and close the tile after a while it will show the configured valves. But a few seconds later, if I closed it again, they will vanish.

**Comment by koryhutchison** [comment]
Thanks for checking out the plugin! And yeah I've noticed this on my own as well. I'm not really sure what's causing it. I kind of just decided that it's the home app that's the problem. For example, I don't see this problem in the Eve app. I'm hoping that when iOS 16 comes out this fall that it fixes this issue. 

So yeah I'm pretty sure it's the Home app that's the problem, not the plugin. But I do suppose there is something I could be doing wrong. But in the mean time, you can always download the free Eve app to use the sprinkler system and it should work well for you.

**Comment by thieren** [comment]
Thx for the reply. Ok I'll check it out.

**Comment by koryhutchison** [comment]
Does the Eve app seem to work for you? It's a bummer that the Home app has issues but hopefully it's fixed in iOS 16. I haven't had a chance to test it out yet. But I'm going to close this now, you can go ahead and comment again or open up a new issue if you're still having troubles.
