### ISSUE TITLE
If I have 2 OpenSprinkler units, how is the best way to set them up via this plugin?

### ISSUE THREAD

**Issue by SeanHama** [koryhutchison/homebridge-opensprinkler-api#6]
**Describe Your Problem:**
I have 2 open sprinkler systems, what is the best way to setup the 2 units via this plugin?

**Comment by koryhutchison** [comment]
Sorry for the late reply! I didn't take into account that someone would want to use 2 different units at the same time. So at this current point, the plugin cannot accommodate that. But I can start working on incorporating that into the plugin. One way you could get around this would be to have 2 different homebridge setups and then just use one OpenSprinkler on each one. That is a little bit of a hassle though so I'll work on the multiple system functionality.

**Comment by SeanHama** [comment]
Thanks mate for the reply. In the interim is there another plugin I can use to get the 2 open spinkler units working on the 1 homebridge RPI? Eager to get both my sprinklers work now that its spring in Sydney.

**Comment by koryhutchison** [comment]
Yeah so I know nothing about the other opensprinkler plugins. But, it does seem like it’s pretty easy to set up multiple homebridge instances on the same device. Check out this doc: https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command#multiple-instances

I’ll get working on that functionality as soon as I can though. Sorry that it isn’t available now!

**Comment by SeanHama** [comment]
Perfect, thanks so much for the responsiveness.

**Comment by koryhutchison** [comment]
So it looks like you have multiple OSBee units so that must be what you're trying to use the plugin for? Since the OSBee API is so different I don't think I'll be able to support it. I wish it was an easy fix to help you out, but it isn't. I do think though that it's probably a good idea to bring the multiple unit support to the plugin.
