### ISSUE TITLE
Cant use this plugin, this error appears in the log TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by SeanHama** [koryhutchison/homebridge-opensprinkler-api#7]
**Describe The Bug:**
Unable to use this plugin, not starting the plugin

[23/09/2021, 19:16:13] [HomebridgeOpenSprinklerApi] TypeError: Cannot read property 'toString' of undefined
    at OpenSprinklerPlatform.createIrrigationSystem (/usr/local/lib/node_modules/homebridge-opensprinkler-api/src/platform.ts:82:54)
    at OpenSprinklerPlatform.setUp (/usr/local/lib/node_modules/homebridge-opensprinkler-api/src/platform.ts:48:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-opensprinkler-api/src/platform.ts:32:9)

**To Reproduce:**
here is my config, Im using Osbee OpenSprinkler
Here is my config, Ive tried md5 password and try the last 3 versions and same issue.

{
            "password": {
                "plain": "<opendoor>"
            },
            "valves": [
                {
                    "name": "ZoneF",
                    "defaultDuration": 60
                }
            ],
            "host": "192.168.0.79:80",
            "pollInterval": 15,
            "rainDelay": 24,
            "platform": "HomebridgeOpenSprinklerApi"
        }

**Expected behavior:**
Should work.

<img width="1135" alt="Screen Shot 2021-09-23 at 7 13 34 pm" src="https://user-images.githubusercontent.com/57736130/134483196-a010b415-238d-4edf-9ec4-095b49c533f3.png">
**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by SeanHama** [comment]
Hi Kory,

More information, I'm using the Osbee? Does this plugin work with Osbee ?

**Comment by koryhutchison** [comment]
Yeah so I didn't even know OSBee was a thing. haha but yeah the plugin was only written for OpenSprinkler. It looks like the API for OSBee is different and more simplified compared to the normal OpenSprinkler API. For the foreseeable future I don't think I'll get around to supporting it. Just because they are so different, and I don't own one myself.

I'm sorry I can't make it work! But yeah the plugin will not work for your device.
